services:
  - type: web
    name: portfolio
    env: python
    plan: free
    region: frankfurt
    rootDir: web
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/projects/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        value: mongodb+srv://kallulpt_db_user:6fxEUxPTWvODrste@clustera.fieldxl.mongodb.net/?appName=ClusterA
      - key: MONGO_DB_NAME
        value: portfolio
      - key: SECRET_KEY
        value: aiza-portfolio-secret-2026-xK9mP3qR
      - key: DEBUG
        value: false
      - key: APP_NAME
        value: Portfolio
      - key: CONTACT_EMAIL
        value: aizamitukallul@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
